# General info
[package]
name = "libwhitebeam"
version = "0.2.0"
authors = ["WhiteBeam Security, Inc."]
edition = "2018"

# Build targets
[lib]
name = "whitebeam"
path = "lib.rs"
crate-type = ["cdylib"]

# Cross-platform dependencies
[dependencies]
libc = { version = "0.2" }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
rusqlite = { version = "0.24", features = ["bundled"] }
linkme = { version = "0.2" }
automod = { version = "1.0" }
# Cryptographic dependencies
sha3 = { version = "0.9" }
blake3 = { version = "0.3" }

[features]
whitelist_test = []
