# General info
[package]
name = "whitebeam-installer"
version = "0.3.0"
authors = ["WhiteBeam Security, Inc."]
edition = "2021"

# Build targets
[[bin]]
name = "whitebeam-installer"

# Cross-platform dependencies
[dependencies]
libc = { version = "0.2" }
